### PR TITLE
Systemd fix rhel

### PR DESCRIPTION
**Pull request by cjestel**
This merges master into our branch from upstream. I have added lines that preserve the functionality for RedHat systems in the templates/systemd-override file.

### CODE REVIEW

**Comment by dugdigg** [comment]
Whoa, you been testing this?  quite a lot of changes.

**Comment by adamcstephens** [comment]
Can we not switch to the upstream module? Why do we need to maintain our fork?

**Comment by adamcstephens** [comment]
We should also probably rebase instead of merge if we have to maintain a fork. Though, I'd rather PR a fix for something against upstream.

**Comment by cjestel** [comment]
https://github.com/covermymeds/puppetlabs-postgresql/commit/93940829b7f23b4a6a60574a72d863a1b84cfa20#diff-093e772f35a288e80a79c9d0f9170dae

The above file is what was changed in the past that didn't work for upstream. I've modified it and plan to push this and whatever tests they need to upstream, but think we will need to maintain our fork until that gets merged.

Everything else in this is just merging their master upstream to my branch. Bill showed me a better way to do that so this change doesn't look as intimidating. I'll close this PR and create a new one

**Pull request closed without merging**
